##数据库配置
#api模块
api:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.92.45.50:3306/mmyx?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    userName: mmyx_admin
    password: Gkao%2002$1
    driver-class-name: com.mysql.cj.jdbc.Driver
  service:
    protocal: https
    host: 127.0.0.1
    port:
    application: /api

#产品接口URL
sku:
  server:
    hostUrl: https://amol.com.cn/stag-product/prod
#地域接口URL
addr:
  server:
    hostUrl: https://amol.com.cn/stag-order
#订单接口URL
order:
  server:
    hostUrl: https://amol.com.cn/stag-order
#售后接口URL
aftersale:
  server:
    hostUrl: https://amol.com.cn/stag-order

###redis 配置
spring:
  redis:
    host: 120.92.76.53
    port: 6379
    password: ihm12345

#配置短信发送服务
SMS:
  SERVER: http://120.92.33.169:8080/hangmei/send
